### ISSUE TITLE
Pathfinding-Problem

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#11]
Pathfinding berechnet nur kürzesten weg zwischen Tanken, berücksichtigt nicht die Geschwindigkeit + Richtung beim Erreichen einer Tanke!! Daher merkwürdige Wegführung mit Umwegen.

**Comment by cbacon93** [comment]
mittlerweile gepatched

**Comment by captain13chris** [comment]
Ich vermute, dass dieser Patch teilweise zu merkwürdigen Ergebnissen führt. Probiere Mal die Seed-Nummer 18. Könnte allerdings mit dem "Tankstellen-in-Pfadnähe" gefixt werden?
