### ISSUE TITLE
Tankstellensuchalgorithmus

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#25]
Manchmal wird ein Tankstellenwegpunkt nicht gelöscht, sobald der Gegner die Tanke erreicht hat. Unsere Wegpunktliste enthält dann 1 Wegpunkt, daher wird nicht nach einer neuen Tanke gesucht (ist im if Befehl so definiert, warum, weiß ich leider um diese Uhrzeit nicht)

**Comment by cbacon93** [comment]
Das liegt daran, dass nur der Letzte Wegpunkt überprüft wird, ob der Gegner diese Tankstelle schon weggefahren hat. Die Mitteltankstelle bleibt außen vor. Die Funktion braucht aber sowieso noch eine aktualisierung. Wenn der Gegner mit großer Wahrscheinlichkeit die Tankstelle vor uns erreicht, müssen wir und auch eine alternativtanke suchen.

**Comment by cbacon93** [comment]
fixed
