### ISSUE TITLE
Angriff stürzt ab

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#26]
Beim Angriff liegen manchmal Punkte in „verbotenen“ Lagen (z.B. Minen, außerhalb des Fensters), da für den zweiten Wegpunkt die Position des Gegners PLUS ein Teil seines Beschleunigungsvektors genutzt wird. Beschleunigt er gerade in Richtung Mine, liegt der Punkt drin und es kann kein Weg dorthin berechnet werden - ABSTURZ

**Comment by cbacon93** [comment]
Liegt daran, dass Punkte außerhalb des Spielfeldes in den Pathfinder gesteckt werden.
Dann gibt es keine gültige gridposition dafür.
Gefixed mit clamp
