### ISSUE TITLE
Tankliste muss geupdated werden, immer wenn der Gegner eine Tanke erreicht

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#28]
Sobald Enemy irgendeine Tanke erreicht, muss geprüft werden, ob diese in unserer Wegpunktliste liegt!

ansonsten kann es immer noch passieren, dass wir eine Tanke kurz nach dem Gegner anfahren, die dann natürlich bereits weg ist.

**Comment by cbacon93** [comment]
ist schon drin

**Comment by captain13chris** [comment]
Hat bei mir eben nicht funktioniert... :(

**Comment by cbacon93** [comment]
Ist der Gegner kurz davor, eine Tankstelle abzusammeln die in unseren waypoints ist, wird die Tankstelle raus genommen und die waypoints neu berechnet. 
Es kommt jedoch manchmal vor, dass er einen Tankstellen doppelt als Target setzt. Dann fährt der Spaceball die Tankstelle ab, geht zur nächsten und fliegt nochmal zurück zur letzten.

**Comment by captain13chris** [comment]
Gut, dass du den Bug spezifiziert hast! ;)

**Comment by cbacon93** [comment]
%waypointlist not empty => append new waypoints
    tankdistance=createTankEvaluation(waypointList{waypointCount});
    next_tanke = tankdistance(1,1);

hier müssten jetzt alle tanken rausgefiltert werden, zu den schon ein waypoint gesetzt wurde

**Comment by captain13chris** [comment]
Dieses Problem ist auch im Folgenden aufgetreten:

Unser letzter Wegpunkt war eine Tanke, die der Gegner dann erreicht hat und somit mehr Tanken hatte, als wir. Trotzdem sind wir nicht geflohen, sondern in Richtung dieses letzten Wegpunktes weiter geflogen. Deshalb hat der Gegner uns natürlich erwischt.
