### ISSUE TITLE
Wegpunktfindung muss aktuelle Richtung unseres SpaceBalls berücksichtigen

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#29]
findWayPoints() muss noch den aktuelle Geschwindigkeitsvektor berücksichtigen!! Einfach gelöst durch mehr Strafpunkte für Nodes „hinter“ uns! Im Moment kann es in der Nähe von Minen beim Verfolgen des Gegners dazu kommen, dass man einen unnötigen Umweg nimmt, da man erst abbremsen muss, um die Mine dann in entgegengesetzter Richtung zu umfahren.

**Comment by cbacon93** [comment]
kann ich machen

**Comment by captain13chris** [comment]
nicht umsetzbar
