### ISSUE TITLE
"Enemy reaches Tanke before us" ist ungenau

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#30]
Ist mir bei einer Testrunde aufgefallen: Wir haben die Tankstelle eher erreicht, als der Gegner, obwohl unsere KI das Gegenteil behauptet hat und noch abbremsen wollte.

Vielleicht können wir in dem Zuge überprüfen, ob wir die Tanke schneller erreichen können und wenn wir Vollgas geben würden und wenn keine Bande oder Mine dahinter ist und evtl. zusätzlich auch noch die nächste Tanke in dieselbe Richtung liegt dann einfach Vollgas auf die Tanke geben?

**Comment by cbacon93** [comment]
Vollgas auf die Tanke, wenn der Gegner auch die Tanke ansteuert. Ja das muss noch rein.

**Comment by cbacon93** [comment]
Zu dem Problem: Unser spaceball sieht schon, dass er die Tankstelle erreichen kann vor dem Gegner, sonst würde er vorher abdrehen und sich eine andere suchen. Das Problem ist, wenn nach der Tankstelle ein steiler Wegpunktwinkel existiert. Dann bremst er vorm Erreichen des Wegpunktes ab. Befindet er sich jetzt in einem "wettrennen" um die Tanke, ist das Abbremsen vorher schlecht, wenn es nicht unbedingt nötig ist. Der rote Spaceball macht das nämlich nicht. Dann kann es sein, dass der rote spaceball trotzdem uns noch überholt und das script merkt, dass der rote spaceball eher da ist.
