### ISSUE TITLE
Emergency Brake teilweise zu stark/unnötig? Muss beobachtet werden!

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#31]
Teilweise bremst der Spaceball sehr stark, auch wenn keine Mine oder Bande in der Nähe ist, nur, weil er einen Punkt etwas overshooten würde. In solchen Situationen die "Emergency Brake" etwas abschwächen?

Es muss allerdings beobachtet werden, ob dies einen Vorteil bringen würde?

**Comment by cbacon93** [comment]
Auf jeden fall. Finetuning ist noch nötig.

**Comment by cbacon93** [comment]
Emergencybreak triggert bei zwei Fällen:
Overshooten des Wegpunktes und (wahrscheinlich das, was du meintest)
unmittelbarer Kollisionskurs mit Bande (kann noch verbessert werden durch 'ausweichen' statt vollbremse)

**Comment by captain13chris** [comment]
Genau, ich meine ersteres
