### ISSUE TITLE
Bremsen teilweise zu stark

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#32]
Wenn hinter einem Wegpunkt frei ist, den Bremsfaktor vor diesem Wegpunkt eventuell verringern? Sonst verlieren wir immer Abstand zum Gegner!
Ist der Bremsfaktor vielleicht zu hoch? Bzw. bei sehr geringem Winkel zum nächsten Wegpunkt erst gar nicht vor dem Wegpunkt bremsen?

Müssen wir noch mal besprechen / testen

**Comment by cbacon93** [comment]
Bremsfaktor kann zu klein sein. Muss aber aufgepasst werden, dass bei zu großem Bremsfaktor under Spaceball übersteuern kann und die Kurven nicht mehr schafft

**Comment by captain13chris** [comment]
Könnte uns da dann die emergencyBrake helfen?

**Comment by cbacon93** [comment]
nein, die ist für sowas eigentlich nicht ausgelegt. Die soll uns nur vorm crashen bewahren, daher würde sie das ganze noch langsamer machen.
emergencyBreak bremst wirklich vollgas gegen die momentane geschwindigkeit um das schlimmste zu verhindern
