### ISSUE TITLE
Verteidigungsverbesserung

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#35]
Im Moment "flieht" unser Spaceball, sobald der Gegner dicht an uns ist und mehr getankt hat, als wir. Er sollte dies aber am Besten nur tun, wenn er nicht noch vor dem Gegner eine Tanke erreichen könnte.

**Comment by cbacon93** [comment]
Da müssten wir uns nochmal zusammen setzen und Defensivtaktiken diskutieren
z.B. Gegner durch enge Kurven zum überschießen bringen
oder schnell von Ecke zu ecke, um den Gegner in die Bande zu steuern
