### ISSUE TITLE
FÜR SPÄTER: Programm schreiben, das statistisch Spiele laufen lässt

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#36]
Ein Programm schreiben, welches "spaceballs.m" mehrfach durchlaufen lässt (>10 mal) und für jedes Spiel festhält, wer gewonnen hat und warum -> Ermöglicht statistische Auswertung, wo Verbesserungsbedarf herrscht.

**Comment by cbacon93** [comment]
Super idee, hatte ich mal angefangen und leider aufgegeben, da durch "clear all" in spaceballs.m alle Variablen gelöscht werden, auch die, die die statistischen Werte aufgefasst haben.
Habe noch nicht versucht, clear all weg zu lassen, weil ich nicht sicher bin ob dann noch alles gut läuft.

**Comment by tkuhle** [comment]
done
