### ISSUE TITLE
Bug in "finding Path to next Tanke"

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#37]
Ab und zu kann es passieren, dass unser Spaceball von Anfang an ununterbrochen in Dauerschleife "finding Path to next Tanke" ausführt und sich natürlich nicht bewegt... Da muss es also noch einen Bug geben!

**Comment by cbacon93** [comment]
ich denke in so einem Fall befindet sich der spaceball von einer Mine eingeschlossen und findet keine gültige startNode. Muss ich mal schauen ob ich da was rekursives zusammenstellen kann, das uns einen gültigen startNode findet.
