### ISSUE TITLE
"enemy reaches Tanke before us" und "finding path to next Tanke" Konflikt

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#38]
Diese beiden Befehle haben sich eine Zeit lang andauernd abgewechselt.

**Comment by cbacon93** [comment]
"enemy reaches Tanke before us" kommt, wenn checkTankenPath() berechnet, dass der Gegner vor uns da sein wird und die spezielle Tankstelle aus unseren waypoints raus nimmt.
findPathToNextTanke() merkt dann aber, dass es zu wenige Wegpunkte gibt und fügt die eben entfernte Tanke wieder hinzu, bevor checkTankenPath() sie wieder entfernt.
Habe eigentlich eine persistent variable eingeführt die das verhindern soll, weiß also nicht genau warum das immer noch passiert. müsste mal jemand intensiv debuggen

**Comment by cbacon93** [comment]
Kommt, wenn Gegner zwei Tankstellen bevor uns anfahren würde. Verursacht aber keine Probleme?
Beobachten

**Comment by cbacon93** [comment]
gelöst
