### ISSUE TITLE
Letzter Tankwegpunkt wird nicht gelöscht, nachdem Gegner die Letzte Tanke vor uns erreicht hat

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#39]
Folgende Vermutung meinerseits: Der Gegner hat eine Tankstelle erreicht und wir haben das gemerkt. Leider war dies die letzte Tanke auf dem Spielfeld, daher konnte keine neue gefunden werden und folglich wurden unsere Wegpunkte nicht gelöscht. Anstatt direkt zum Fliehen-Programm zu wechseln, sind wir erst noch zu der bereits verschwundenen Tanke gefahren.

**Comment by cbacon93** [comment]
siehe https://github.com/cbacon93/escalators/issues/28
es KANN nur das erste Element von waypointList gelöscht werden, die Wegpunkte die angeblich nicht gelöscht werden sind nicht an erster stelle, sondern es handelt sich um den versuch, die nächste Tankstelle anzufahren, zu der aber schon waypoints gesetzt wurde
