### ISSUE TITLE
Bande getroffen!

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#40]
Trotz der emergency Brake haben wir eine Bande getroffen... :(

**Comment by captain13chris** [comment]
Und jetzt hat er doch tatsächlich ne Mine getroffen :'(

Kann das am "Zeitraffer" liegen, weil dieser ungenauer ist?

**Comment by cbacon93** [comment]
nein, das liegt am sich leicht ändernden Geschwindigkeitsvektor, oder daran. dass es wirklich erst Bremst wenn er mit minimaler Sicherheit zum stehen kommen kann.
Wie gesagt emergencyBreak entgegen der Geschwindigkeitsrichtung ist nicht immer am schlausten, gerade wenn man den Gegner verfolgt und leicht links oder rechts vorbei dem Hindernis ausweichen kann. Deshalb braucht die Funktion sowieso noch überholung

**Comment by captain13chris** [comment]
safeDeleteWayoiunts() neu schreiben!

**Comment by cbacon93** [comment]
closed:
#43 
#44
