### ISSUE TITLE
zeitraffer einschalten führt zu spiel abbruch

### ISSUE THREAD

**Issue by tkuhle** [cbacon93/escalators#45]
Error using drawnow
Unknown command option.

Error in spielfeld_aktualisieren (line 281)
    drawnow limitrate

Error in schritt (line 228)
spielfeld_aktualisieren (spiel, video);
Error in spaceballs (line 96)
    spiel = schritt (spiel, video);

Error in statistics (line 8)
        spaceballs

**Comment by cbacon93** [comment]
Ist kein Fehler bei unserem script
"spielfeld_aktualisieren (line 281)"
