### ISSUE TITLE
emergencyBreak berücksichtigt nicht die Änderung des Geschwindigkeitsvektors

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/escalators#46]
emergencyBreak muss noch schauen, dass wir nicht zufällig eine Mine schneiden, während wir die Bewegungsrichtung verändern

**Comment by captain13chris** [comment]
die Emergency Brake verursacht zur Zeit überhaupt keine Richtungsänderung... Die tritt nur voll auf die Bremse

**Comment by cbacon93** [comment]
Richtig, emergencyBreak bremst aber nur zu einem gewissen Prozentsatz. Üblicherweise 70% Bremsen und 30% übernimmt zwischendurch wieder die Steuerung, um nicht völlig den Kurs zu verlieren. Aber die Steuerung kann den Spaceball auch manchmal unabsichtig in eine Mine lenken. Jetzt wird aber auch die Beschleunigung betrachtet und verhindert ein in die Mine lenken. Leider setzt das emergencyBreak nun noch früher ein. Aber signifikant verschlechtert hat sich unsere Spaceball performance nicht.
