### ISSUE TITLE
Verteidigungstaktik: Ausweichen mit Bande

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/escalators#50]
Habe folgenden Vorschlag als Verteidigungstaktik:
Unser Spaceball versucht so schnell wie möglich zur Bande zu kommen und kurz davor stehen zu bleiben. Der Gegner wird nun mit hoher Geschwindigkeit angeflogen kommen und ebenfalls vor der Bande abbremsen. Jetzt müssen wir mit voller Beschleunigung im rechten Winkel ausweichen. Da der Gegner abbremsen muss, um nicht in die Bande zu rauschen kann er nicht so stark in unsere Richtung beschleunigen wie wir. Sobald wir aus der Gefahrenzone des Gegners sind, fliegen wir zur Bande gegenüber und wiederholen das ganze.

**Comment by captain13chris** [comment]
Hat Julian inzwischen umgesetzt, allerdings in den Ecken.
