### ISSUE TITLE
Corner Tricking failed bei Seed 1149

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/escalators#52]
Bei Seed 1149 hat der gegnerische Spaceball unseren erwischt
Zum Finetuning ;)

**Comment by captain13chris** [comment]
Gefixt durch Erhöhung des constCompetitionModeThreshold auf 0.1

Muss weiter beobachtet werden!

**Comment by cbacon93** [comment]
Dann schließe ich das erstmal, machen dann ne neue issue auf wenn wir eine entsprechende seed haben
