### ISSUE TITLE
Emergency Brake versagt!

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#57]
702456
773785
720746

**Comment by cbacon93** [comment]
ganz lustig: wir testen beim emergency break die Endpunkte also wo wir bei einer Vollbremsung sein würden, auf Kollisionen, aber nicht den Raum dazwischen. Bei den Seeds schafft unser Spaceball es, eine Mine zwischen sich und besagten Endpunkt zu kriegen.
Solved ;)

**Comment by cbacon93** [comment]
Achja: wollte erst die Bremskonstanten hochdrehen, dann währe unser Spaceball aber langsamer geworden. zum Glück war das nicht nötig ;)
