### ISSUE TITLE
Attack mode Verbesserung

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#58]
Der projezierte Punkt im "direct attack" mode liegt nicht weit genug in Richtung des gegnerischen Geschwindigkeitsvektors. Bei kleinen Entfernungen klappt das gut, bei großen Entfernungen fahren wir dem Gegner nur hinterher, anstatt ihm den Weg abzuschneiden.

**Comment by cbacon93** [comment]
Problem: Bei großen Entfernungen ist die Extrapolation zu ungenau, wenn der Gegner oft die Beschleunigungsrichtung ändert, dann eiern wir hinterher, deshalb ist in der Extrapolationsberechnung ein Limit gesetzt, dass erst ab einer Gewissen Ankunftszeit zum Gegner extrapoliert wird. 
Folgender Lösungsvorschlag: wir könnten statt der Zeit, den Weg zum Gegner als Limit setzen. Bei Verfolgungen wo die Zeit eigentlich sehr groß ist, aber der Gegner nicht weit entfernt ist sollte das helfen.

**Comment by cbacon93** [comment]
Hab das mal gemacht. Braucht mal noch ein wenig Beobachtung

**Comment by cbacon93** [comment]
Ich hab gerade lustiges festgestellt: wisst ihr noch wie unser Spaceball immer schneller war, wenn der Gegner Schlangenlinien gefahren ist? wir versuchen jetzt ihn in der Kurve abzufangen und schlängeln mit. Sind also nicht mehr schneller. Könnte behoben werden, wenn das Distanzlimit zum extrapolieren kleiner gesetzt wird. Dann fängt er aber den Gegner nicht mehr so gut an Ecken ab. Wir unterscheidet man jetzt Schlangenlinien von anderen Kurven? Ableitung des Geschwindigkeitsvektors abschätzen? Oder wieder rückgängig machen?

**Comment by cbacon93** [comment]
Gelöst
