### ISSUE TITLE
Entscheidung über competition mode verbesserungswürdig

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#59]
In einigen Spielen wäre es besser, wenn unser Spaceball (früher oder überhaupt) in den competition mode ginge. Im Moment bemerkt er, dass der Gegner eher da sein könnte und sucht sich gleich eine neue Tanke. Leider wäre die vom Gegner nun erreichte Tanke sehr wichtig für uns gewesen (da sie z.B. die mittlere ist).

Vielleicht den comp-mode-threshold für die mittlere Tankstelle höher setzen?

**Comment by cbacon93** [comment]
Sidenote: comp-mode-threshold ist die Zeit, die der Gegner eher da sein darf und wir trotzdem versuchen zur Tanke zu fahren. Zu große Erhöhung kann sehr gefährlich werden und oft zur Niederlage führen. Deswegen eventuell kleine Schritterhöhung mit statistischer Auswertung.
Sollte der Unterschied unserer Ankunftszeit und der des Gegners größer sein als diese Konstante, sucht er sich eine neue Tanke. Eventuell ist auch eine zusätzliche Bedingung für den competitionmode nötig.

**Comment by cbacon93** [comment]
Haben so viel dran rum geschraubt, ich schließe das mal und öffne es wieder. Falls es konkrete seeds gibt
