### ISSUE TITLE
Mine entgegengesetzt umfahren

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#60]
Fährt der Gegner mit einer bestimmten Geschwindigkeit hinter einer Mine, sollte unser Spaceball diese entgegengesetzt umfahren und nicht nur stumpf hinterherdackeln. Könnte mit Lösung von Problem #58 behoben werden.

**Comment by cbacon93** [comment]
Ist durch dauerhaftes Interpolieren und Smoothing so gut es geht gelöst
