### ISSUE TITLE
Minenoptimierung

### ISSUE THREAD

**Issue by tkuhle** [cbacon93/escalators#61]
matlab auswertung.
Statistische_Erhebung = 

    'Lauf Nr.:  1'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  2'      [0]    'Verloren'     'Zeit ist abgelaufen.'    'Seed: 25198' 
    'Lauf Nr.:  3'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  4'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  5'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  6'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  7'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  8'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  9'      [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  10'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 919839'
    'Lauf Nr.:  11'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  12'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  13'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  14'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 226007'
    'Lauf Nr.:  15'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  16'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 627761'
    'Lauf Nr.:  17'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  18'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  19'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  20'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  21'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  22'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  23'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  24'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 913463'
    'Lauf Nr.:  25'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  26'     [0]    'Verloren'     'Zeit ist abgelaufen.'    'Seed: 540642'
    'Lauf Nr.:  27'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  28'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  29'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  30'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  31'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  32'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 584246'
    'Lauf Nr.:  33'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  34'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  35'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  36'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  37'     [0]    'Verloren'     'Blau trifft Bande.'      'Seed: 203537'
    'Lauf Nr.:  38'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  39'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 553354'
    'Lauf Nr.:  40'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 683351'
    'Lauf Nr.:  41'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  42'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  43'     [0]    'Verloren'     'Zeit ist abgelaufen.'    'Seed: 203400'
    'Lauf Nr.:  44'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  45'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  46'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 375181'
    'Lauf Nr.:  47'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 104026'
    'Lauf Nr.:  48'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  49'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 632475'
    'Lauf Nr.:  50'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  51'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  52'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  53'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  54'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  55'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  56'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  57'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  58'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 973379'
    'Lauf Nr.:  59'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  60'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 733253'
    'Lauf Nr.:  61'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  62'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  63'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  64'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  65'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 947466'
    'Lauf Nr.:  66'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 448373'
    'Lauf Nr.:  67'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  68'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  69'     [0]    'Verloren'     'Blau trifft Bande.'      'Seed: 625829'
    'Lauf Nr.:  70'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  71'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  72'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  73'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 669374'
    'Lauf Nr.:  74'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  75'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  76'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  77'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  78'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  79'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  80'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  81'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  82'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  83'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  84'     [0]    'Verloren'     'Zeit ist abgelaufen.'    'Seed: 698865'
    'Lauf Nr.:  85'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  86'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 439169'
    'Lauf Nr.:  87'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  88'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  89'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  90'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  91'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  92'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 601231'
    'Lauf Nr.:  93'     [0]    'Verloren'     'Zeit ist abgelaufen.'    'Seed: 612774'
    'Lauf Nr.:  94'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  95'     [0]    'Verloren'     'Rot trifft Blau.'        'Seed: 854501'
    'Lauf Nr.:  96'     [0]    'Verloren'     'Blau trifft Mine.'       'Seed: 125439'
    'Lauf Nr.:  97'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  98'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  99'     [1]    'Gewonnnen'    ' '                       ' '           
    'Lauf Nr.:  100'    [1]    'Gewonnnen'    ' '                       ' '           

>>

**Comment by cbacon93** [comment]
Also habe das gerade mal nachgetestet. Mit der neuen Emergencybreak hatte ich bei ersten 10 Kollisionsseeds keine Kollisionen mehr. Die Liste kann also nochmal aktualisiert werden ;)
