### ISSUE TITLE
Wegpunkte auf Tanken werden nicht gelöscht, obwohl Gegner die Tanken eingesammelt hat!

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#72]
386153 ohne Minen testen!

**Comment by cbacon93** [comment]
also bei mir haben wir da gewonnen, und das wie oben beschrieben passier nicht

**Comment by cbacon93** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/4532320/10663495/423d834a-78bc-11e5-8d18-f8afb22fe910.JPG)

**Comment by captain13chris** [comment]
Hab eine Videoaufzeichnung in den escalators Hauptordner bei Dropbox kopiert... Mit welcher Version hattest du getestet?

**Comment by cbacon93** [comment]
Sehr gut, ich schau mir das mal heute an.

**Comment by captain13chris** [comment]
mit neuestem Master gefixt
