### ISSUE TITLE
Warum wird competitionMode hier nicht aktiviert?

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#73]
215803 ohne Minen laufen lassen. Es geht um die letzte Tanke!

**Comment by captain13chris** [comment]
Hmm. Wir müssten eh bremsen, da wir sonst in die Bande fahren, also brächte der compMode auch nichts

**Comment by cbacon93** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/4532320/10663459/e38d1fd6-78bb-11e5-8a2d-920bf5558d05.JPG)

wir fahren sonst leider in die Bande. Der Gegner ist dagegen viel näher dran und hat einen besseren Winkel
