### ISSUE TITLE
Notbremse ist ineffizient

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#74]
# 292277

Im Moment bremsen wir weg vom Gegner. In diesem Fall fahren wir daher einen unnötigen Kreis und verlieren dadurch das Spiel. Wir sollten in der Notbremse lieber knapp am Gegner vorbei fahren, als komplett zu bremsen.

**Comment by cbacon93** [comment]
wie wärs wenn wir den Winkel zwischen uns und dem Gegner als Ausweichpunkt nehmen?

**Comment by captain13chris** [comment]
ist so halbwegs umgesetzt, aber deutlich verbesserungswürdig!
