### ISSUE TITLE
Statistik 24.10

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/escalators#77]
We don't C#, we MethLab  VS  Halbwertszeit
 
Von 250 Spielen wurden 217 in durchschnittlich 24.915 Sekunden gewonnen.
 
 
Gewonnen: 86.8 %
   davon den Gegner erwischt: 97.235 %
 
Verloren: 5.2 %
   davon in Mine gefahren: 0 %
   davon in Bande gefahren: 15.3846 %
 
Unentschieden im Angriff: 5.2 %
 
Unentschieden in der Verteidigung: 2.8 %
 
Error: 0 %
 
 
    '1'      'Gewonnnen'              'Blau trifft Rot.'        [ 6.3000]    '# 953067'
    '2'      'Gewonnnen'              'Blau trifft Rot.'        [31.9800]    '# 647829'
    '3'      'Gewonnnen'              'Blau trifft Rot.'        [18.4800]    '# 896715'
    '4'      'Gewonnnen'              'Blau trifft Rot.'        [15.2900]    '# 375132'
    '5'      'Gewonnnen'              'Blau trifft Rot.'        [23.9500]    '# 152742'
    '6'      'Gewonnnen'              'Blau trifft Rot.'        [15.6400]    '# 340539'
    '7'      'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 410631'
    '8'      'Gewonnnen'              'Blau trifft Rot.'        [22.7100]    '# 830793'
    '9'      'Gewonnnen'              'Blau trifft Rot.'        [18.8500]    '# 517462'
    '10'     'Gewonnnen'              'Blau trifft Rot.'        [34.2400]    '# 696356'
    '11'     'Gewonnnen'              'Blau trifft Rot.'        [18.5600]    '# 882220'
    '12'     'Gewonnnen'              'Blau trifft Rot.'        [20.7900]    '# 137089'
    '13'     'Gewonnnen'              'Blau trifft Rot.'        [15.3200]    '# 508555'
    '14'     'Gewonnnen'              'Blau trifft Rot.'        [14.0300]    '# 329493'
    '15'     'Gewonnnen'              'Blau trifft Rot.'        [31.2500]    '# 725891'
    '16'     'Gewonnnen'              'Blau trifft Rot.'        [44.6000]    '# 204531'
    '17'     'Verloren'               'Rot trifft Blau.'        [10.2800]    '# 17451' 
    '18'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 765446'
    '19'     'Gewonnnen'              'Blau trifft Rot.'        [32.3300]    '# 66041' 
    '20'     'Gewonnnen'              'Blau trifft Rot.'        [18.6100]    '# 888568'
    '21'     'Gewonnnen'              'Blau trifft Rot.'        [16.9300]    '# 375174'
    '22'     'Gewonnnen'              'Blau trifft Rot.'        [14.3500]    '# 678826'
    '23'     'Gewonnnen'              'Blau trifft Rot.'        [17.4100]    '# 956502'
    '24'     'Verloren'               'Rot trifft Blau.'        [14.4700]    '# 503496'
    '25'     'Gewonnnen'              'Blau trifft Rot.'        [15.6200]    '# 536099'
    '26'     'Gewonnnen'              'Blau trifft Rot.'        [17.0800]    '# 718192'
    '27'     'Gewonnnen'              'Blau trifft Rot.'        [10.2800]    '# 909131'
    '28'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 649368'
    '29'     'Gewonnnen'              'Blau trifft Rot.'        [31.6400]    '# 327122'
    '30'     'Gewonnnen'              'Blau trifft Rot.'        [20.5500]    '# 819772'
    '31'     'Gewonnnen'              'Blau trifft Rot.'        [19.5400]    '# 928957'
    '32'     'Gewonnnen'              'Blau trifft Rot.'        [17.6600]    '# 979393'
    '33'     'Gewonnnen'              'Blau trifft Rot.'        [37.8900]    '# 285078'
    '34'     'Verloren'               'Rot trifft Blau.'        [ 3.4500]    '# 685333'
    '35'     'Gewonnnen'              'Blau trifft Rot.'        [ 9.4600]    '# 147778'
    '36'     'Gewonnnen'              'Blau trifft Rot.'        [17.1600]    '# 136089'
    '37'     'Gewonnnen'              'Blau trifft Rot.'        [28.0500]    '# 347306'
    '38'     'Gewonnnen'              'Blau trifft Rot.'        [18.4700]    '# 26592' 
    '39'     'Gewonnnen'              'Blau trifft Rot.'        [18.9200]    '# 704542'
    '40'     'Gewonnnen'              'Blau trifft Rot.'        [30.4900]    '# 986006'
    '41'     'Gewonnnen'              'Blau trifft Rot.'        [26.2400]    '# 669995'
    '42'     'Gewonnnen'              'Blau trifft Rot.'        [17.0100]    '# 905380'
    '43'     'Gewonnnen'              'Blau trifft Rot.'        [12.4200]    '# 912249'
    '44'     'Gewonnnen'              'Blau trifft Rot.'        [15.8000]    '# 688374'
    '45'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 815061'
    '46'     'Gewonnnen'              'Blau trifft Rot.'        [36.0200]    '# 9230'  
    '47'     'Gewonnnen'              'Blau trifft Rot.'        [25.6500]    '# 268773'
    '48'     'Gewonnnen'              'Blau trifft Rot.'        [16.5700]    '# 135479'
    '49'     'Gewonnnen'              'Blau trifft Rot.'        [37.5400]    '# 700974'
    '50'     'Gewonnnen'              'Blau trifft Rot.'        [16.5800]    '# 916308'
    '51'     'Gewonnnen'              'Blau trifft Rot.'        [25.2900]    '# 795681'
    '52'     'Gewonnnen'              'Blau trifft Rot.'        [16.3900]    '# 967160'
    '53'     'Gewonnnen'              'Blau trifft Rot.'        [59.2200]    '# 959814'
    '54'     'Gewonnnen'              'Blau trifft Rot.'        [27.1600]    '# 155287'
    '55'     'Gewonnnen'              'Blau trifft Rot.'        [22.6400]    '# 492566'
    '56'     'Gewonnnen'              'Blau trifft Rot.'        [53.9400]    '# 406036'
    '57'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 549363'
    '58'     'Gewonnnen'              'Blau trifft Rot.'        [18.3500]    '# 962981'
    '59'     'Gewonnnen'              'Blau trifft Rot.'        [18.6300]    '# 315163'
    '60'     'Gewonnnen'              'Blau trifft Rot.'        [27.9900]    '# 561120'
    '61'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 984403'
    '62'     'Gewonnnen'              'Blau trifft Rot.'        [19.2500]    '# 841225'
    '63'     'Gewonnnen'              'Blau trifft Rot.'        [28.0400]    '# 361784'
    '64'     'Gewonnnen'              'Blau trifft Rot.'        [19.9000]    '# 872492'
    '65'     'Gewonnnen'              'Blau trifft Rot.'        [ 7.0200]    '# 442107'
    '66'     'Gewonnnen'              'Blau trifft Rot.'        [39.6000]    '# 2738'  
    '67'     'Gewonnnen'              'Blau trifft Rot.'        [31.1400]    '# 816413'
    '68'     'Gewonnnen'              'Blau trifft Rot.'        [19.2800]    '# 190031'
    '69'     'Gewonnnen'              'Blau trifft Rot.'        [ 5.4000]    '# 968781'
    '70'     'Gewonnnen'              'Blau trifft Rot.'        [14.7300]    '# 372534'
    '71'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 74667' 
    '72'     'Gewonnnen'              'Blau trifft Rot.'        [37.6100]    '# 70910' 
    '73'     'Gewonnnen'              'Blau trifft Rot.'        [45.9100]    '# 827027'
    '74'     'Verloren'               'Rot trifft Blau.'        [      8]    '# 818319'
    '75'     'Verloren'               'Rot trifft Blau.'        [ 3.7900]    '# 810165'
    '76'     'Gewonnnen'              'Blau trifft Rot.'        [35.6400]    '# 478114'
    '77'     'Gewonnnen'              'Blau trifft Rot.'        [48.6000]    '# 815204'
    '78'     'Gewonnnen'              'Blau trifft Rot.'        [22.1900]    '# 42027' 
    '79'     'Gewonnnen'              'Blau trifft Rot.'        [39.6100]    '# 836782'
    '80'     'Gewonnnen'              'Blau trifft Rot.'        [16.1900]    '# 597269'
    '81'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 419430'
    '82'     'Gewonnnen'              'Blau trifft Rot.'        [32.3100]    '# 164301'
    '83'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 8148'  
    '84'     'Gewonnnen'              'Blau trifft Rot.'        [ 9.9400]    '# 839437'
    '85'     'Gewonnnen'              'Blau trifft Rot.'        [51.4600]    '# 987660'
    '86'     'Gewonnnen'              'Blau trifft Rot.'        [20.5400]    '# 468276'
    '87'     'Gewonnnen'              'Blau trifft Rot.'        [22.6100]    '# 893153'
    '88'     'Gewonnnen'              'Blau trifft Rot.'        [25.2900]    '# 126042'
    '89'     'Gewonnnen'              'Blau trifft Rot.'        [36.8000]    '# 52708' 
    '90'     'Gewonnnen'              'Blau trifft Rot.'        [21.2700]    '# 665189'
    '91'     'Gewonnnen'              'Blau trifft Rot.'        [38.1900]    '# 706847'
    '92'     'Gewonnnen'              'Blau trifft Rot.'        [20.1500]    '# 775496'
    '93'     'Gewonnnen'              'Blau trifft Rot.'        [21.8100]    '# 541024'
    '94'     'Gewonnnen'              'Blau trifft Rot.'        [14.5600]    '# 937372'
    '95'     'Gewonnnen'              'Blau trifft Rot.'        [18.8500]    '# 17984' 
    '96'     'Gewonnnen'              'Blau trifft Rot.'        [31.8900]    '# 277827'
    '97'     'Gewonnnen'              'Rot trifft Mine.'        [27.1500]    '# 840469'
    '98'     'Gewonnnen'              'Blau trifft Rot.'        [32.1100]    '# 986551'
    '99'     'Gewonnnen'              'Blau trifft Rot.'        [29.1400]    '# 445962'
    '100'    'Gewonnnen'              'Blau trifft Rot.'        [18.3200]    '# 329478'
    '101'    'Gewonnnen'              'Blau trifft Rot.'        [22.1500]    '# 124589'
    '102'    'Gewonnnen'              'Blau trifft Rot.'        [17.1600]    '# 931796'
    '103'    'Verloren'               'Rot trifft Blau.'        [ 7.6400]    '# 442456'
    '104'    'Gewonnnen'              'Blau trifft Rot.'        [20.0700]    '# 556576'
    '105'    'Gewonnnen'              'Blau trifft Rot.'        [25.7400]    '# 960154'
    '106'    'Gewonnnen'              'Blau trifft Rot.'        [38.0200]    '# 449275'
    '107'    'Gewonnnen'              'Blau trifft Rot.'        [26.1700]    '# 460454'
    '108'    'Gewonnnen'              'Blau trifft Rot.'        [24.1800]    '# 118499'
    '109'    'Gewonnnen'              'Blau trifft Rot.'        [17.9200]    '# 481548'
    '110'    'Gewonnnen'              'Blau trifft Rot.'        [36.7800]    '# 250361'
    '111'    'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 586611'
    '112'    'Gewonnnen'              'Blau trifft Rot.'        [ 4.9800]    '# 106318'
    '113'    'Gewonnnen'              'Blau trifft Rot.'        [47.9000]    '# 925913'
    '114'    'Gewonnnen'              'Blau trifft Rot.'        [16.0100]    '# 176631'
    '115'    'Verloren'               'Rot trifft Blau.'        [ 4.1600]    '# 624611'
    '116'    'Gewonnnen'              'Blau trifft Rot.'        [19.2200]    '# 747614'
    '117'    'Gewonnnen'              'Blau trifft Rot.'        [     20]    '# 290559'
    '118'    'Gewonnnen'              'Blau trifft Rot.'        [20.6100]    '# 282553'
    '119'    'Gewonnnen'              'Blau trifft Rot.'        [18.6300]    '# 794516'
    '120'    'Gewonnnen'              'Blau trifft Rot.'        [31.1800]    '# 14466' 
    '121'    'Gewonnnen'              'Blau trifft Rot.'        [16.1200]    '# 608292'
    '122'    'Verloren'               'Blau trifft Bande.'      [23.1800]    '# 403876'
    '123'    'Gewonnnen'              'Blau trifft Rot.'        [59.3800]    '# 323331'
    '124'    'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 67128' 
    '125'    'Gewonnnen'              'Blau trifft Rot.'        [20.3200]    '# 444499'
    '126'    'Gewonnnen'              'Blau trifft Rot.'        [16.4800]    '# 708043'
    '127'    'Gewonnnen'              'Blau trifft Rot.'        [59.9800]    '# 79098' 
    '128'    'Gewonnnen'              'Blau trifft Rot.'        [14.7300]    '# 247299'
    '129'    'Gewonnnen'              'Blau trifft Rot.'        [15.8700]    '# 610089'
    '130'    'Gewonnnen'              'Blau trifft Rot.'        [21.4900]    '# 411756'
    '131'    'Gewonnnen'              'Blau trifft Rot.'        [26.4900]    '# 664031'
    '132'    'Gewonnnen'              'Blau trifft Rot.'        [22.8700]    '# 244087'
    '133'    'Gewonnnen'              'Blau trifft Rot.'        [ 5.7500]    '# 962880'
    '134'    'Gewonnnen'              'Rot trifft Mine.'        [44.9000]    '# 437531'
    '135'    'Gewonnnen'              'Blau trifft Rot.'        [49.4500]    '# 404206'
    '136'    'Gewonnnen'              'Blau trifft Rot.'        [32.8300]    '# 596371'
    '137'    'Gewonnnen'              'Blau trifft Rot.'        [13.3700]    '# 451600'
    '138'    'Gewonnnen'              'Blau trifft Rot.'        [17.4300]    '# 190824'
    '139'    'Gewonnnen'              'Blau trifft Rot.'        [22.8400]    '# 496939'
    '140'    'Gewonnnen'              'Blau trifft Rot.'        [19.0400]    '# 758457'
    '141'    'Gewonnnen'              'Blau trifft Rot.'        [27.7900]    '# 413198'
    '142'    'Gewonnnen'              'Blau trifft Rot.'        [17.4300]    '# 569483'
    '143'    'Gewonnnen'              'Blau trifft Rot.'        [16.1800]    '# 321976'
    '144'    'Gewonnnen'              'Blau trifft Rot.'        [23.7500]    '# 391414'
    '145'    'Gewonnnen'              'Blau trifft Rot.'        [39.1100]    '# 659239'
    '146'    'Gewonnnen'              'Blau trifft Rot.'        [19.7500]    '# 597164'
    '147'    'Gewonnnen'              'Rot trifft Mine.'        [16.5500]    '# 638213'
    '148'    'Gewonnnen'              'Blau trifft Rot.'        [18.3300]    '# 77144' 
    '149'    'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 873491'
    '150'    'Gewonnnen'              'Blau trifft Rot.'        [17.6700]    '# 755975'
    '151'    'Gewonnnen'              'Blau trifft Rot.'        [53.7700]    '# 85329' 
    '152'    'Gewonnnen'              'Blau trifft Rot.'        [17.4100]    '# 73351' 
    '153'    'Verloren'               'Rot trifft Blau.'        [ 3.9800]    '# 575633'
    '154'    'Gewonnnen'              'Blau trifft Rot.'        [23.9500]    '# 747012'
    '155'    'Gewonnnen'              'Blau trifft Rot.'        [22.9600]    '# 686392'
    '156'    'Gewonnnen'              'Blau trifft Rot.'        [ 5.1500]    '# 600159'
    '157'    'Gewonnnen'              'Blau trifft Rot.'        [16.8700]    '# 74059' 
    '158'    'Gewonnnen'              'Blau trifft Rot.'        [24.5300]    '# 126063'
    '159'    'Gewonnnen'              'Blau trifft Rot.'        [22.4400]    '# 25295' 
    '160'    'Gewonnnen'              'Blau trifft Rot.'        [18.7800]    '# 6458'  
    '161'    'Gewonnnen'              'Blau trifft Rot.'        [16.9800]    '# 801028'
    '162'    'Gewonnnen'              'Rot trifft Mine.'        [ 6.9700]    '# 901613'
    '163'    'Gewonnnen'              'Blau trifft Rot.'        [14.0400]    '# 858624'
    '164'    'Gewonnnen'              'Blau trifft Rot.'        [26.7700]    '# 435545'
    '165'    'Gewonnnen'              'Blau trifft Rot.'        [13.6800]    '# 515875'
    '166'    'Gewonnnen'              'Blau trifft Rot.'        [44.2800]    '# 274059'
    '167'    'Gewonnnen'              'Blau trifft Rot.'        [25.2300]    '# 673546'
    '168'    'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 503360'
    '169'    'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 688660'
    '170'    'Gewonnnen'              'Blau trifft Rot.'        [27.8400]    '# 599363'
    '171'    'Gewonnnen'              'Blau trifft Rot.'        [14.9300]    '# 249266'
    '172'    'Gewonnnen'              'Blau trifft Rot.'        [59.0800]    '# 913588'
    '173'    'Gewonnnen'              'Blau trifft Rot.'        [24.1400]    '# 927001'
    '174'    'Gewonnnen'              'Blau trifft Rot.'        [31.6200]    '# 238142'
    '175'    'Gewonnnen'              'Blau trifft Rot.'        [15.6900]    '# 619148'
    '176'    'Gewonnnen'              'Blau trifft Rot.'        [19.6800]    '# 138193'
    '177'    'Gewonnnen'              'Blau trifft Rot.'        [21.6800]    '# 289101'
    '178'    'Gewonnnen'              'Blau trifft Rot.'        [21.7900]    '# 52888' 
    '179'    'Gewonnnen'              'Blau trifft Rot.'        [17.9400]    '# 999048'
    '180'    'Gewonnnen'              'Blau trifft Rot.'        [24.1900]    '# 572034'
    '181'    'Gewonnnen'              'Blau trifft Rot.'        [27.1200]    '# 507277'
    '182'    'Gewonnnen'              'Blau trifft Rot.'        [28.8700]    '# 860955'
    '183'    'Verloren'               'Rot trifft Blau.'        [17.5900]    '# 983553'
    '184'    'Gewonnnen'              'Blau trifft Rot.'        [20.0100]    '# 799334'
    '185'    'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 988492'
    '186'    'Gewonnnen'              'Blau trifft Rot.'        [43.4500]    '# 2100'  
    '187'    'Gewonnnen'              'Blau trifft Rot.'        [21.5300]    '# 288994'
    '188'    'Gewonnnen'              'Blau trifft Rot.'        [18.0200]    '# 490528'
    '189'    'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 502774'
    '190'    'Gewonnnen'              'Blau trifft Rot.'        [18.3100]    '# 808933'
    '191'    'Gewonnnen'              'Blau trifft Rot.'        [54.6600]    '# 126921'
    '192'    'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 434605'
    '193'    'Gewonnnen'              'Blau trifft Rot.'        [19.1000]    '# 509528'
    '194'    'Gewonnnen'              'Blau trifft Rot.'        [13.0800]    '# 56745' 
    '195'    'Gewonnnen'              'Blau trifft Rot.'        [23.2300]    '# 260290'
    '196'    'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 946205'
    '197'    'Gewonnnen'              'Blau trifft Rot.'        [59.8200]    '# 918139'
    '198'    'Gewonnnen'              'Blau trifft Rot.'        [26.6100]    '# 446159'
    '199'    'Verloren'               'Blau trifft Bande.'      [58.0300]    '# 729068'
    '200'    'Gewonnnen'              'Blau trifft Rot.'        [38.7400]    '# 109687'
    '201'    'Verloren'               'Rot trifft Blau.'        [10.7900]    '# 652929'
    '202'    'Gewonnnen'              'Blau trifft Rot.'        [22.6500]    '# 40718' 
    '203'    'Gewonnnen'              'Blau trifft Rot.'        [40.7400]    '# 505619'
    '204'    'Gewonnnen'              'Blau trifft Rot.'        [ 7.0900]    '# 902310'
    '205'    'Gewonnnen'              'Blau trifft Rot.'        [31.2800]    '# 257432'
    '206'    'Gewonnnen'              'Blau trifft Rot.'        [22.0200]    '# 568368'
    '207'    'Gewonnnen'              'Blau trifft Rot.'        [18.2400]    '# 216513'
    '208'    'Gewonnnen'              'Blau trifft Rot.'        [16.3500]    '# 603117'
    '209'    'Gewonnnen'              'Blau trifft Rot.'        [33.3400]    '# 531324'
    '210'    'Gewonnnen'              'Blau trifft Rot.'        [13.6000]    '# 10291' 
    '211'    'Gewonnnen'              'Blau trifft Rot.'        [14.7100]    '# 665064'
    '212'    'Gewonnnen'              'Blau trifft Rot.'        [32.1600]    '# 814648'
    '213'    'Gewonnnen'              'Blau trifft Rot.'        [17.2700]    '# 324555'
    '214'    'Gewonnnen'              'Blau trifft Rot.'        [14.7500]    '# 580416'
    '215'    'Gewonnnen'              'Blau trifft Rot.'        [14.7500]    '# 31347' 
    '216'    'Gewonnnen'              'Blau trifft Rot.'        [28.7300]    '# 503010'
    '217'    'Gewonnnen'              'Blau trifft Rot.'        [24.2500]    '# 617445'
    '218'    'Gewonnnen'              'Blau trifft Rot.'        [25.3600]    '# 303033'
    '219'    'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 872172'
    '220'    'Gewonnnen'              'Blau trifft Rot.'        [23.7100]    '# 787321'
    '221'    'Gewonnnen'              'Blau trifft Rot.'        [59.6500]    '# 254384'
    '222'    'Gewonnnen'              'Blau trifft Rot.'        [22.5000]    '# 318668'
    '223'    'Gewonnnen'              'Blau trifft Rot.'        [59.8300]    '# 585164'
    '224'    'Gewonnnen'              'Blau trifft Rot.'        [46.0400]    '# 138763'
    '225'    'Gewonnnen'              'Blau trifft Rot.'        [57.5500]    '# 561996'
    '226'    'Gewonnnen'              'Blau trifft Rot.'        [11.5100]    '# 458343'
    '227'    'Gewonnnen'              'Blau trifft Rot.'        [24.2200]    '# 203036'
    '228'    'Gewonnnen'              'Blau trifft Rot.'        [27.6700]    '# 333852'
    '229'    'Gewonnnen'              'Blau trifft Rot.'        [ 7.9000]    '# 520294'
    '230'    'Gewonnnen'              'Blau trifft Rot.'        [23.0600]    '# 329737'
    '231'    'Gewonnnen'              'Blau trifft Rot.'        [21.4300]    '# 28006' 
    '232'    'Gewonnnen'              'Rot trifft Mine.'        [31.3700]    '# 958028'
    '233'    'Gewonnnen'              'Blau trifft Rot.'        [20.6000]    '# 180644'
    '234'    'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 724793'
    '235'    'Gewonnnen'              'Rot trifft Mine.'        [23.2800]    '# 374724'
    '236'    'Gewonnnen'              'Blau trifft Rot.'        [13.8900]    '# 173059'
    '237'    'Gewonnnen'              'Blau trifft Rot.'        [ 9.0700]    '# 380579'
    '238'    'Gewonnnen'              'Blau trifft Rot.'        [ 8.2500]    '# 523204'
    '239'    'Gewonnnen'              'Blau trifft Rot.'        [28.7800]    '# 220826'
    '240'    'Verloren'               'Rot trifft Blau.'        [17.2400]    '# 355300'
    '241'    'Gewonnnen'              'Blau trifft Rot.'        [24.0800]    '# 181071'
    '242'    'Gewonnnen'              'Blau trifft Rot.'        [23.5300]    '# 329915'
    '243'    'Gewonnnen'              'Blau trifft Rot.'        [30.9700]    '# 600060'
    '244'    'Gewonnnen'              'Blau trifft Rot.'        [23.2900]    '# 319059'
    '245'    'Gewonnnen'              'Blau trifft Rot.'        [32.5100]    '# 910736'
    '246'    'Gewonnnen'              'Blau trifft Rot.'        [36.1900]    '# 734691'
    '247'    'Gewonnnen'              'Blau trifft Rot.'        [15.0700]    '# 801978'
    '248'    'Gewonnnen'              'Blau trifft Rot.'        [40.3400]    '# 135743'
    '249'    'Gewonnnen'              'Blau trifft Rot.'        [26.4400]    '# 545218'
    '250'    'Gewonnnen'              'Blau trifft Rot.'        [28.6100]    '# 566482'

**Comment by cbacon93** [comment]
Die Bandenkollisionen wurden gefixt

**Comment by captain13chris** [comment]
ist überholt
