### ISSUE TITLE
Statistik 24.10.2015 ohne Minen

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/escalators#79]
We don't C#, we MethLab  VS  Halbwertszeit
 
Von 100 Spielen wurden 77 in durchschnittlich 19.7869 Sekunden gewonnen.
 
 
Gewonnen: 77 %
   davon den Gegner erwischt: 100 %
 
Verloren: 7 %
   davon in Mine gefahren: 0 %
   davon in Bande gefahren: 0 %
 
Unentschieden im Angriff: 0 %
 
Unentschieden in der Verteidigung: 16 %
 
Error: 0 %
 
 
    '1'      'Gewonnnen'              'Blau trifft Rot.'       [20.2800]    '# 399640'
    '2'      'Gewonnnen'              'Blau trifft Rot.'       [17.5900]    '# 499225'
    '3'      'Gewonnnen'              'Blau trifft Rot.'       [15.8100]    '# 282092'
    '4'      'Gewonnnen'              'Blau trifft Rot.'       [22.3300]    '# 236859'
    '5'      'Gewonnnen'              'Blau trifft Rot.'       [ 6.8300]    '# 653834'
    '6'      'Gewonnnen'              'Blau trifft Rot.'       [27.2500]    '# 134667'
    '7'      'Gewonnnen'              'Blau trifft Rot.'       [22.2800]    '# 461088'
    '8'      'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 878403'
    '9'      'Gewonnnen'              'Blau trifft Rot.'       [20.2500]    '# 507959'
    '10'     'Gewonnnen'              'Blau trifft Rot.'       [18.3800]    '# 663066'
    '11'     'Gewonnnen'              'Blau trifft Rot.'       [15.7500]    '# 242616'
    '12'     'Gewonnnen'              'Blau trifft Rot.'       [14.8800]    '# 73971' 
    '13'     'Gewonnnen'              'Blau trifft Rot.'       [19.3800]    '# 221162'
    '14'     'Gewonnnen'              'Blau trifft Rot.'       [31.1300]    '# 390341'
    '15'     'Gewonnnen'              'Blau trifft Rot.'       [22.6300]    '# 633787'
    '16'     'Gewonnnen'              'Blau trifft Rot.'       [22.0300]    '# 628523'
    '17'     'Gewonnnen'              'Blau trifft Rot.'       [22.8200]    '# 6567'  
    '18'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 121407'
    '19'     'Gewonnnen'              'Blau trifft Rot.'       [      9]    '# 677440'
    '20'     'Gewonnnen'              'Blau trifft Rot.'       [21.6100]    '# 929149'
    '21'     'Gewonnnen'              'Blau trifft Rot.'       [15.1000]    '# 577686'
    '22'     'Gewonnnen'              'Blau trifft Rot.'       [26.4300]    '# 877685'
    '23'     'Gewonnnen'              'Blau trifft Rot.'       [17.1500]    '# 917012'
    '24'     'Verloren'               'Rot trifft Blau.'       [20.0500]    '# 153613'
    '25'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 750516'
    '26'     'Gewonnnen'              'Blau trifft Rot.'       [ 8.1500]    '# 962136'
    '27'     'Gewonnnen'              'Blau trifft Rot.'       [20.3800]    '# 103716'
    '28'     'Gewonnnen'              'Blau trifft Rot.'       [23.1900]    '# 169991'
    '29'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 889080'
    '30'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 955535'
    '31'     'Gewonnnen'              'Blau trifft Rot.'       [34.6100]    '# 179330'
    '32'     'Gewonnnen'              'Blau trifft Rot.'       [23.7700]    '# 372303'
    '33'     'Verloren'               'Rot trifft Blau.'       [ 3.9600]    '# 316829'
    '34'     'Gewonnnen'              'Blau trifft Rot.'       [ 7.5000]    '# 176734'
    '35'     'Gewonnnen'              'Blau trifft Rot.'       [16.6700]    '# 610008'
    '36'     'Gewonnnen'              'Blau trifft Rot.'       [22.3400]    '# 238239'
    '37'     'Gewonnnen'              'Blau trifft Rot.'       [16.9600]    '# 710235'
    '38'     'Gewonnnen'              'Blau trifft Rot.'       [20.3100]    '# 66961' 
    '39'     'Verloren'               'Rot trifft Blau.'       [14.1800]    '# 546423'
    '40'     'Gewonnnen'              'Blau trifft Rot.'       [16.3000]    '# 543839'
    '41'     'Gewonnnen'              'Blau trifft Rot.'       [17.5300]    '# 655400'
    '42'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 60654' 
    '43'     'Gewonnnen'              'Blau trifft Rot.'       [20.7300]    '# 517320'
    '44'     'Gewonnnen'              'Blau trifft Rot.'       [20.7400]    '# 831099'
    '45'     'Verloren'               'Rot trifft Blau.'       [20.4500]    '# 438562'
    '46'     'Gewonnnen'              'Blau trifft Rot.'       [14.5500]    '# 224193'
    '47'     'Gewonnnen'              'Blau trifft Rot.'       [20.1300]    '# 964897'
    '48'     'Gewonnnen'              'Blau trifft Rot.'       [26.3800]    '# 877705'
    '49'     'Gewonnnen'              'Blau trifft Rot.'       [18.3000]    '# 31219' 
    '50'     'Gewonnnen'              'Blau trifft Rot.'       [14.5500]    '# 94049' 
    '51'     'Gewonnnen'              'Blau trifft Rot.'       [28.3100]    '# 864289'
    '52'     'Gewonnnen'              'Blau trifft Rot.'       [20.7600]    '# 644967'
    '53'     'Gewonnnen'              'Blau trifft Rot.'       [15.8200]    '# 133605'
    '54'     'Gewonnnen'              'Blau trifft Rot.'       [14.7000]    '# 703353'
    '55'     'Gewonnnen'              'Blau trifft Rot.'       [24.9500]    '# 715373'
    '56'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 761920'
    '57'     'Gewonnnen'              'Blau trifft Rot.'       [     28]    '# 793928'
    '58'     'Gewonnnen'              'Blau trifft Rot.'       [29.4700]    '# 832829'
    '59'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 388582'
    '60'     'Verloren'               'Rot trifft Blau.'       [14.5300]    '# 166405'
    '61'     'Gewonnnen'              'Blau trifft Rot.'       [18.1500]    '# 81435' 
    '62'     'Gewonnnen'              'Blau trifft Rot.'       [16.9400]    '# 701398'
    '63'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 453503'
    '64'     'Gewonnnen'              'Blau trifft Rot.'       [16.5500]    '# 183427'
    '65'     'Gewonnnen'              'Blau trifft Rot.'       [25.7400]    '# 403786'
    '66'     'Gewonnnen'              'Blau trifft Rot.'       [31.0800]    '# 533618'
    '67'     'Gewonnnen'              'Blau trifft Rot.'       [21.4300]    '# 177225'
    '68'     'Gewonnnen'              'Blau trifft Rot.'       [19.3900]    '# 70488' 
    '69'     'Gewonnnen'              'Blau trifft Rot.'       [17.7800]    '# 88098' 
    '70'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 2607'  
    '71'     'Verloren'               'Rot trifft Blau.'       [17.5500]    '# 900392'
    '72'     'Gewonnnen'              'Blau trifft Rot.'       [23.5600]    '# 427338'
    '73'     'Gewonnnen'              'Blau trifft Rot.'       [19.7300]    '# 550089'
    '74'     'Verloren'               'Rot trifft Blau.'       [17.2600]    '# 214575'
    '75'     'Gewonnnen'              'Blau trifft Rot.'       [16.1600]    '# 446180'
    '76'     'Gewonnnen'              'Blau trifft Rot.'       [13.7300]    '# 692200'
    '77'     'Gewonnnen'              'Blau trifft Rot.'       [15.1600]    '# 782399'
    '78'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 93702' 
    '79'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 706315'
    '80'     'Gewonnnen'              'Blau trifft Rot.'       [17.9200]    '# 510780'
    '81'     'Gewonnnen'              'Blau trifft Rot.'       [23.5400]    '# 894979'
    '82'     'Gewonnnen'              'Blau trifft Rot.'       [20.3000]    '# 276387'
    '83'     'Gewonnnen'              'Blau trifft Rot.'       [18.6300]    '# 29334' 
    '84'     'Gewonnnen'              'Blau trifft Rot.'       [16.9000]    '# 507988'
    '85'     'Gewonnnen'              'Blau trifft Rot.'       [18.0600]    '# 358556'
    '86'     'Gewonnnen'              'Blau trifft Rot.'       [18.2800]    '# 789907'
    '87'     'Gewonnnen'              'Blau trifft Rot.'       [18.0100]    '# 413226'
    '88'     'Gewonnnen'              'Blau trifft Rot.'       [ 5.5400]    '# 934637'
    '89'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 97835' 
    '90'     'Gewonnnen'              'Blau trifft Rot.'       [19.2100]    '# 51214' 
    '91'     'Gewonnnen'              'Blau trifft Rot.'       [25.8500]    '# 103774'
    '92'     'Gewonnnen'              'Blau trifft Rot.'       [35.7900]    '# 452207'
    '93'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 839607'
    '94'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 647465'
    '95'     'Gewonnnen'              'Blau trifft Rot.'       [22.1800]    '# 194598'
    '96'     'Unent. Verteidigung'    'Zeit ist abgelauf…'     [     60]    '# 374931'
    '97'     'Gewonnnen'              'Blau trifft Rot.'       [23.3200]    '# 69962' 
    '98'     'Gewonnnen'              'Blau trifft Rot.'       [13.4900]    '# 589874'
    '99'     'Gewonnnen'              'Blau trifft Rot.'       [21.8100]    '# 414042'
    '100'    'Gewonnnen'              'Blau trifft Rot.'       [15.3500]    '# 360613'

**Comment by captain13chris** [comment]
ist überholt
