### ISSUE TITLE
Statistik 25.10.2015

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/escalators#80]
We don't C#, we MethLab  VS  Halbwertszeit
 
Von 100 Spielen wurden 74 in durchschnittlich 29.1599 Sekunden gewonnen.
 
 
Gewonnen: 74 %
   davon den Gegner erwischt: 91.8919 %
 
Verloren: 12 %
   davon in Mine gefahren: 0 %
   davon in Bande gefahren: 16.6667 %
 
Unentschieden im Angriff: 6 %
 
Unentschieden in der Verteidigung: 8 %
 
Error: 0 %
 
 
    '1'      'Gewonnnen'              'Blau trifft Rot.'        [18.6100]    '# 942009'
    '2'      'Gewonnnen'              'Blau trifft Rot.'        [24.9000]    '# 249298'
    '3'      'Gewonnnen'              'Rot trifft Mine.'        [22.2300]    '# 104404'
    '4'      'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 696668'
    '5'      'Gewonnnen'              'Blau trifft Rot.'        [17.1600]    '# 450115'
    '6'      'Gewonnnen'              'Blau trifft Rot.'        [28.8000]    '# 271319'
    '7'      'Verloren'               'Rot trifft Blau.'        [13.5800]    '# 543892'
    '8'      'Gewonnnen'              'Blau trifft Rot.'        [53.4300]    '# 135234'
    '9'      'Verloren'               'Blau trifft Bande.'      [ 1.1900]    '# 69335' 
    '10'     'Gewonnnen'              'Blau trifft Rot.'        [17.1700]    '# 202527'
    '11'     'Gewonnnen'              'Rot trifft Mine.'        [28.4000]    '# 779639'
    '12'     'Verloren'               'Rot trifft Blau.'        [19.4800]    '# 438819'
    '13'     'Gewonnnen'              'Blau trifft Rot.'        [35.4200]    '# 481491'
    '14'     'Gewonnnen'              'Blau trifft Rot.'        [32.6100]    '# 416045'
    '15'     'Gewonnnen'              'Blau trifft Rot.'        [30.9100]    '# 34307' 
    '16'     'Gewonnnen'              'Blau trifft Rot.'        [53.7000]    '# 625117'
    '17'     'Gewonnnen'              'Blau trifft Rot.'        [15.2100]    '# 162056'
    '18'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 377995'
    '19'     'Gewonnnen'              'Blau trifft Rot.'        [59.9900]    '# 794396'
    '20'     'Verloren'               'Rot trifft Blau.'        [ 4.5400]    '# 343134'
    '21'     'Verloren'               'Rot trifft Blau.'        [20.5000]    '# 637202'
    '22'     'Gewonnnen'              'Blau trifft Rot.'        [22.2300]    '# 813280'
    '23'     'Gewonnnen'              'Blau trifft Rot.'        [26.6900]    '# 101933'
    '24'     'Gewonnnen'              'Rot trifft Mine.'        [23.7900]    '# 948475'
    '25'     'Gewonnnen'              'Blau trifft Rot.'        [38.6500]    '# 641734'
    '26'     'Gewonnnen'              'Blau trifft Rot.'        [27.4200]    '# 814792'
    '27'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 825014'
    '28'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 210208'
    '29'     'Gewonnnen'              'Blau trifft Rot.'        [15.9800]    '# 448270'
    '30'     'Gewonnnen'              'Blau trifft Rot.'        [37.4200]    '# 497040'
    '31'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 711913'
    '32'     'Gewonnnen'              'Rot trifft Mine.'        [ 8.6700]    '# 123928'
    '33'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 99737' 
    '34'     'Gewonnnen'              'Blau trifft Rot.'        [52.4900]    '# 835786'
    '35'     'Gewonnnen'              'Blau trifft Rot.'        [48.9200]    '# 985100'
    '36'     'Gewonnnen'              'Blau trifft Rot.'        [15.2000]    '# 7773'  
    '37'     'Gewonnnen'              'Blau trifft Rot.'        [13.5000]    '# 188469'
    '38'     'Gewonnnen'              'Blau trifft Rot.'        [ 4.5500]    '# 155135'
    '39'     'Verloren'               'Rot trifft Blau.'        [30.3000]    '# 207064'
    '40'     'Gewonnnen'              'Blau trifft Rot.'        [30.8100]    '# 503054'
    '41'     'Gewonnnen'              'Blau trifft Rot.'        [51.5700]    '# 597653'
    '42'     'Verloren'               'Blau trifft Bande.'      [24.6900]    '# 718200'
    '43'     'Gewonnnen'              'Blau trifft Rot.'        [39.7600]    '# 240280'
    '44'     'Gewonnnen'              'Blau trifft Rot.'        [14.0700]    '# 744835'
    '45'     'Gewonnnen'              'Blau trifft Rot.'        [46.1300]    '# 26226' 
    '46'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 977396'
    '47'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 724803'
    '48'     'Gewonnnen'              'Rot trifft Mine.'        [ 7.6200]    '# 919842'
    '49'     'Gewonnnen'              'Blau trifft Rot.'        [47.7700]    '# 792556'
    '50'     'Gewonnnen'              'Blau trifft Rot.'        [20.5200]    '# 683372'
    '51'     'Gewonnnen'              'Blau trifft Rot.'        [24.7800]    '# 389225'
    '52'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 230440'
    '53'     'Gewonnnen'              'Blau trifft Rot.'        [43.1500]    '# 166304'
    '54'     'Gewonnnen'              'Blau trifft Rot.'        [31.8500]    '# 986131'
    '55'     'Gewonnnen'              'Blau trifft Rot.'        [40.9000]    '# 319046'
    '56'     'Gewonnnen'              'Blau trifft Rot.'        [ 8.5600]    '# 135539'
    '57'     'Gewonnnen'              'Blau trifft Rot.'        [29.5100]    '# 493961'
    '58'     'Gewonnnen'              'Rot trifft Mine.'        [     22]    '# 267066'
    '59'     'Gewonnnen'              'Blau trifft Rot.'        [24.8600]    '# 520230'
    '60'     'Gewonnnen'              'Blau trifft Rot.'        [10.2000]    '# 785042'
    '61'     'Gewonnnen'              'Blau trifft Rot.'        [53.8100]    '# 274728'
    '62'     'Gewonnnen'              'Blau trifft Rot.'        [28.7000]    '# 16730' 
    '63'     'Verloren'               'Rot trifft Blau.'        [30.2900]    '# 936815'
    '64'     'Verloren'               'Rot trifft Blau.'        [15.2500]    '# 859427'
    '65'     'Gewonnnen'              'Blau trifft Rot.'        [14.4200]    '# 17197' 
    '66'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 386948'
    '67'     'Gewonnnen'              'Blau trifft Rot.'        [54.0900]    '# 577297'
    '68'     'Gewonnnen'              'Blau trifft Rot.'        [22.8600]    '# 787265'
    '69'     'Gewonnnen'              'Blau trifft Rot.'        [ 5.2800]    '# 434184'
    '70'     'Gewonnnen'              'Blau trifft Rot.'        [ 9.7500]    '# 792240'
    '71'     'Gewonnnen'              'Blau trifft Rot.'        [ 5.6000]    '# 215720'
    '72'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 644949'
    '73'     'Gewonnnen'              'Blau trifft Rot.'        [20.3100]    '# 986161'
    '74'     'Gewonnnen'              'Blau trifft Rot.'        [54.0500]    '# 969637'
    '75'     'Gewonnnen'              'Blau trifft Rot.'        [34.4100]    '# 562166'
    '76'     'Gewonnnen'              'Blau trifft Rot.'        [ 9.9000]    '# 337710'
    '77'     'Gewonnnen'              'Blau trifft Rot.'        [13.2800]    '# 706211'
    '78'     'Gewonnnen'              'Blau trifft Rot.'        [16.4100]    '# 389901'
    '79'     'Verloren'               'Rot trifft Blau.'        [ 3.7400]    '# 971619'
    '80'     'Gewonnnen'              'Blau trifft Rot.'        [53.7300]    '# 618492'
    '81'     'Gewonnnen'              'Blau trifft Rot.'        [20.1500]    '# 494450'
    '82'     'Gewonnnen'              'Blau trifft Rot.'        [     21]    '# 889582'
    '83'     'Gewonnnen'              'Blau trifft Rot.'        [40.9500]    '# 155504'
    '84'     'Gewonnnen'              'Blau trifft Rot.'        [48.3200]    '# 440341'
    '85'     'Gewonnnen'              'Blau trifft Rot.'        [41.4200]    '# 676749'
    '86'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 410357'
    '87'     'Gewonnnen'              'Blau trifft Rot.'        [28.0900]    '# 450422'
    '88'     'Gewonnnen'              'Blau trifft Rot.'        [30.0700]    '# 459311'
    '89'     'Gewonnnen'              'Blau trifft Rot.'        [34.7100]    '# 466949'
    '90'     'Unent. Angriff'         'Zeit ist abgelaufen.'    [     60]    '# 417190'
    '91'     'Gewonnnen'              'Blau trifft Rot.'        [33.8300]    '# 296335'
    '92'     'Gewonnnen'              'Blau trifft Rot.'        [40.8000]    '# 936123'
    '93'     'Gewonnnen'              'Blau trifft Rot.'        [31.4500]    '# 221742'
    '94'     'Gewonnnen'              'Blau trifft Rot.'        [34.3400]    '# 364263'
    '95'     'Verloren'               'Rot trifft Blau.'        [10.9900]    '# 218217'
    '96'     'Gewonnnen'              'Blau trifft Rot.'        [37.6400]    '# 4372'  
    '97'     'Verloren'               'Rot trifft Blau.'        [10.1300]    '# 24124' 
    '98'     'Unent. Verteidigung'    'Zeit ist abgelaufen.'    [     60]    '# 389581'
    '99'     'Gewonnnen'              'Blau trifft Rot.'        [19.3600]    '# 929228'
    '100'    'Gewonnnen'              'Blau trifft Rot.'        [30.9900]    '# 676051'

**Comment by cbacon93** [comment]
@jwigge wahrscheinlich für dich Interessant sind die Seeds bei denen wir verloren haben. Leider hat unser Spaceball noch oft die falsche Ecke angesteuert und wurde dabei vom Gegner abgefangen.

**Comment by captain13chris** [comment]
ist überholt
