### ISSUE TITLE
Competition Mode-Abbrechen löst fehlerhaft aus

### ISSUE THREAD

**Issue by captain13chris** [cbacon93/escalators#83]
514120 bei diesem Seed gehen wir erst in den comp-Mode und machen dann ne Notbremsung, obwohl wir es locker schaffen, sogar mit der Notbremsung...

**Comment by cbacon93** [comment]
Bei mir haben wir da verloren, aber er setzt die Notbremse nicht in die richtige Richtung

**Comment by cbacon93** [comment]
Noch aktuell wegen #da5763b6e08a03dc5fcfb62dc10d39122c9798ea

**Comment by cbacon93** [comment]
cd160ce

**Comment by captain13chris** [comment]
gefixt.
